services:

  parking_app:
    container_name: parking_app
    build:
      dockerfile: ./app/Dockerfile
    restart: on-failure
    volumes:
      - ./app/:/var/www
    ports:
      - "9000:80"


  messenger:
    container_name: messenger
    build:
      dockerfile: ./app/Dockerfile-messenger
    restart: on-failure
    volumes:
      - ./app/:/var/www

networks:
  default:
    name: developer
    external: true